### ISSUE TITLE
Transaction debug failed

### ISSUE THREAD

**Issue by liverbirdkte** [ckb-ecofund/offckb#143]
I started a offckb node with devnet, when I was trying to use debug command to dump a transaction, I got the following error:

```
lei@lei:~/offckb$ offckb debug --tx-hash 0xb6f8d378e55b4c21812fd9853ed0765303c76e11756f0870ecd9923a4e3a30fc
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: ENOENT: no such file or directory, open '/home/lei/.local/share/offckb-nodejs/devnet/transactions/0xb6f8d378e55b4c21812fd9853ed0765303c76e11756f0870ecd9923a4e3a30fc.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/lei/.local/share/offckb-nodejs/devnet/transactions/0xb6f8d378e55b4c21812fd9853ed0765303c76e11756f0870ecd9923a4e3a30fc.json'
}

Node.js v20.17.0
Command failed: Command failed: /home/lei/.nvm/versions/node/v20.17.0/lib/node_modules/@offckb/cli/node_modules/.bin/ckb-transaction-dumper --rpc http://localhost:8114 --tx "/home/lei/.local/share/offckb-nodejs/devnet/transactions/0xb6f8d378e55b4c21812fd9853ed0765303c76e11756f0870ecd9923a4e3a30fc.json" --output "/home/lei/.local/share/offckb-nodejs/devnet/full-transactions/0xb6f8d378e55b4c21812fd9853ed0765303c76e11756f0870ecd9923a4e3a30fc.json"
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/home/lei/.local/share/offckb-nodejs/devnet/transactions/0xb6f8d378e55b4c21812fd9853ed0765303c76e11756f0870ecd9923a4e3a30fc.json'
    at Object.readFileSync (node:fs:448:20)
    at buildTransactionDebugOptions (/home/lei/.nvm/versions/node/v20.17.0/lib/node_modules/@offckb/cli/dist/cmd/debug.js:27:44)
    at debugTransaction (/home/lei/.nvm/versions/node/v20.17.0/lib/node_modules/@offckb/cli/dist/cmd/debug.js:16:18)
    at /home/lei/.nvm/versions/node/v20.17.0/lib/node_modules/@offckb/cli/dist/cli.js:150:41
    at Generator.next (<anonymous>)
    at /home/lei/.nvm/versions/node/v20.17.0/lib/node_modules/@offckb/cli/dist/cli.js:32:71
    at new Promise (<anonymous>)
    at __awaiter (/home/lei/.nvm/versions/node/v20.17.0/lib/node_modules/@offckb/cli/dist/cli.js:28:12)
    at Command.<anonymous> (/home/lei/.nvm/versions/node/v20.17.0/lib/node_modules/@offckb/cli/dist/cli.js:144:25)
    at Command.listener [as _actionHandler] (/home/lei/.nvm/versions/node/v20.17.0/lib/node_modules/@offckb/cli/node_modules/commander/lib/command.js:542:17) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/lei/.local/share/offckb-nodejs/devnet/transactions/0xb6f8d378e55b4c21812fd9853ed0765303c76e11756f0870ecd9923a4e3a30fc.json'
}

Node.js v20.17.0 
```

It looks like the error is from https://github.com/ckb-ecofund/offckb/blob/master/src/cmd/debug.ts#L92, the json file of txJsonFilePath doesn't exist, thus the dump fails. I'm wondering if we could just pass the tx hash to the dumper instread of a tx file.

**Comment by RetricSu** [comment]
normally the transaction json file will be generated by the offckb automatically when you calling `offckb debug --tx-hash ...` One thing to note is that you must use the RPC proxy url(which is locahost:9000 by default, not localhost:8114) to make the transaction first so that offckb can remember that transaction. 

So in that case, how did you made your tx `0xb6f8d378e55b4c21812fd9853ed0765303c76e11756f0870ecd9923a4e3a30fc` ?, can you try using the local node proxy RPC `localhost:9000` to sending transactions and then calling `offckb debug --tx-hash ...` ?

**Comment by liverbirdkte** [comment]
Thanks for quick answer. 

Yes, I launched two services, a node without proxy and a proxy server running on port 9000.

The tx hash is from contract deployment, I deployed contracts from ckb-hands-on-example, and use that hash for debugging. Also tried with frontend transfer tx hash, same error raised. 

Could you point to me where this transaction file is generated in the code, then I could make some checks on my local env.

**Comment by RetricSu** [comment]
> Thanks for quick answer.
> 
> Yes, I launched two services, a node without proxy and a proxy server running on port 9000.
> 
> The tx hash is from contract deployment, I deployed contracts from ckb-hands-on-example, and use that hash for debugging. Also tried with frontend transfer tx hash, same error raised.
> 
> Could you point to me where this transaction file is generated in the code, then I could make some checks on my local env.

so if you using `offckb deploy` to deploy contracts that transaction is unforunatly targeting on node rpc with port 8114, not through the proxy rpc server so offckb won't remember the transaction. (maybe we need to update offckb deploy to make it targeting on proxy rpc). as for `frontend transfer` i am not sure if that is targeting on proxy RPC or just node RPC.

for the code, the transaction will first be recorded here https://github.com/ckb-ecofund/offckb/blob/master/src/tools/rpc-proxy.ts#L37-L51 through the RPC proxy, and then use the recorded transaction file to dump the full transation file here https://github.com/ckb-ecofund/offckb/blob/master/src/cmd/debug.ts#L83-L96

**Comment by RetricSu** [comment]
so to make it clear, you need to use proxy RPC to submit your transaction to blockchain first if you want to use `offckb debug` with the hash of that transaction.

**Comment by liverbirdkte** [comment]
OK, got it. Offckb has a separate RPC proxy which records transaction info, thus tools directly talk to ckb RPC service(like using Lumos) don't generate transaction file. Thanks!
