### ISSUE TITLE
how to change chain name in offckb？

### ISSUE THREAD

**Issue by rink1969** [ckb-ecofund/offckb#144]
我用offckb开发框架，用offckb node命令跑了一个dev节点。
但是当我用ckb-cli查询链上信息的时候，遇到一个报错
$ ./ckb-cli --url http://localhost:9000/ util cell-meta --tx-hash 0x4660f484fe2e3db4c8acb92e3be5592735b6ac6edcebbff815b2b203039bb8d7 --index 0
Unexpected network type: offckb
我看了ckb-cli的代码，chain的名称需要是ckb_dev才能识别。怎么改offckb的配置，让链名称是ckb_dev？

我尝试过手工修改dev.toml文件，但是改了之后offckb命令就不能工作了。

**Comment by RetricSu** [comment]
这里我考虑把链的名称默认设置为 ckb_dev, 或许没有必要用一个特殊的名称？另外增加一个配置选项或许也是可以的，我尝试一下

**Comment by RetricSu** [comment]
另外，

> 我尝试过手工修改dev.toml文件，但是改了之后offckb命令就不能工作了。

这个dev.toml 是在配置里面的 devnet.configPath 文件夹里修改的吗？修改完报错信息是什么？如果修改完后先把配置里面的 devnet.dataPath 的链数据清空再重启还会报错吗？btw，可以使用 `offckb config list` 看到各路径信息

**Comment by rink1969** [comment]
是的，修改的devnet/spec/dev.toml
改完要清理链的数据的，不然节点就会报错

这里说的offckb命令不能工作是指运行`offckb sync-scripts`会报错

**Comment by RetricSu** [comment]
> 是的，修改的devnet/spec/dev.toml 改完要清理链的数据的，不然节点就会报错
> 
> 这里说的offckb命令不能工作是指运行`offckb sync-scripts`会报错

明白，我发布了一个修复，可以看下是否能解决问题 `npm install -g @offckb/cli@0.3.0-canary-3b77560.0`？

**Comment by rink1969** [comment]
> 明白，我发布了一个修复，可以看下是否能解决问题 `npm install -g @offckb/cli@0.3.0-canary-3b77560.0`？

我试了一下，链的名称改了，而且没有之前的报错了
但是有一个新的错误
```
$ ~/.local/share/offckb-nodejs/bins/0.113.1/ckb-cli --debug  --url http://localhost:9000 util cell-meta --tx-hash 0x4660f484fe2e3db4c8acb92e3be5592735b6ac6edcebbff815b2b203039bb8d7 --index 1
http error: `error decoding response body: EOF while parsing a value at line 1 column 0`
```

**Comment by RetricSu** [comment]
> > 明白，我发布了一个修复，可以看下是否能解决问题 `npm install -g @offckb/cli@0.3.0-canary-3b77560.0`？
> 
> 我试了一下，链的名称改了，而且没有之前的报错了 但是有一个新的错误
> 
> ```
> $ ~/.local/share/offckb-nodejs/bins/0.113.1/ckb-cli --debug  --url http://localhost:9000 util cell-meta --tx-hash 0x4660f484fe2e3db4c8acb92e3be5592735b6ac6edcebbff815b2b203039bb8d7 --index 1
> http error: `error decoding response body: EOF while parsing a value at line 1 column 0`
> ```

奇怪，我这里试了下这个命令，好像无法复现。

```sh
 ~/Library/Application Support/offckb-nodejs/bins/0.113.1  ./ckb-cli --debug  --url http://localhost:9000 util cell-meta --tx-hash 0xa52ba451f1566d60f9004bd59f28ad97fac9bb5fbbc9bbb50940e33ec5b45cdb --index 0
address: ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2prryvze6fhufxkgjx35psh7w70k3hz7c3mtl4d
data_hash: 0x1465ce82be2d4ae54e3688440a5612da10924e29ba8924011182aafa80a003b4
lock_hash: 0x4472b33b4e1845ebe82f2ce5f511bbe012f144c5f3d7b539909adffc83ccda61
output:
  capacity: 0x1c90beaee00
  lock:
    args: 0x4118c8c16749bf126b22468d030bf9de7da3717b
    code_hash: 0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8
    hash_type: type
  type:
    args: 0x3e1938daba26ed460e29f47a45ce2c92e4a7410467a79ab4904a423473b2d212
    code_hash: 0x00000000000000000000000000000000000000000000000000545950455f4944
    hash_type: type
type_hash: 0x5ea4b9d50093a19943dc788c15bbdf7cd9d89efd67989a18b162feca814d90bb
```
and 

```sh
 ~/Library/Application Support/offckb-nodejs/bins/0.113.1  ./ckb-cli --debug  --url http://localhost:9000 util cell-meta --tx-hash 0x4660f484fe2e3db4c8acb92e3be5592735b6ac6edcebbff815b2b203039bb8d7 --index 1
cell: ~
status: unknown
```

**Comment by rink1969** [comment]
ok，可以了
已经查明后面这个报错是我本地环境的问题

**Comment by RetricSu** [comment]
增加了文档 
- https://github.com/ckb-ecofund/offckb?tab=readme-ov-file#tweak-devnet-config
