### ISSUE TITLE
redeploy same contract not upgrade？

### ISSUE THREAD

**Issue by rink1969** [ckb-ecofund/offckb#150]
我用offckb创建了一个Dapp工程
用`offckb node 0.118.0` 跑了一个开发节点
用 `offckb deploy --network devnet`部署了自带的`hello-world`合约

然后我修改了合约代码重新编译，并重新用 `offckb deploy --network devnet`部署
因为自带的`hello-world`合约是打开了`enable_type_id`即可升级合约，我理解重新部署的行为应该是升级合约
但是实际操作下来发现是又部署了一个新合约

我尝试把deployment.toml和migrations文件拷贝出来，参考 https://github.com/nervosnetwork/ckb-cli/wiki/Deploy-contracts 用`ckb-cli`进行合约升级的操作
然后在生成合约升级交易命令时，上述两个文件格式有一些报错
```
~/.local/share/offckb-nodejs/bins/0.118.0/ckb-cli --url http://localhost:9000 deploy gen-txs --deployment-config ./deployment.toml --migration-dir ./migrations --from-address ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2prryvze6fhufxkgjx35psh7w70k3hz7c3mtl4d --info-file update-tx.json

invalid type: string "true", expected a boolean for key `cells.enable_type_id` at line 3 column 18

invalid type: string "0x0", expected u32 at line 6 column 20

invalid type: string "0x4b58", expected u64 at line 7 column 35
```
我手工修改文件
deployment.toml里的enable_type_id需要从字符串改成bool
migrations/2024-10-12-151416.json里的index需要从字符串改成u8；occupied_capacity需要从字符串改成u64后面还要加8个0
然后就可以升级合约了

问题：
1. 我理解对于打开了`enable_type_id`的合约，重新部署的行为应该是升级合约。我的理解是否正确？如果不是的话，是否有参数控制这个行为？
2. 那几个格式错误是offckb没有适配最新的ckb版本吗？

**Comment by RetricSu** [comment]
1. 目前只是使用 type id 方式来部署，但是还没有做同一个合约升级的功能。打算增加一个参数 --type-id 来显性地指明部署类型，然后自动做升级合约的部署。如果没有指定参数，则使用 data 不可升级的方式部署
2. 属于格式细节上没对齐的 bug，会根据 ckb-cli 的格式来修复

**Comment by RetricSu** [comment]
1. todo
2. https://github.com/ckb-ecofund/offckb/pull/152
