### ISSUE TITLE
specify ckb version

### ISSUE THREAD

**Issue by sunchengzhu** [ckb-ecofund/offckb#75]
Can a feature be added to specify the CKB version with a parameter in the offckb node?
for example：`offckb node v0.116.0-rc2`

**Comment by RetricSu** [comment]
good idea. i will think about it

**Comment by RetricSu** [comment]
this is now avaliable in [v0.3.0-rc1](https://github.com/ckb-ecofund/offckb/releases/tag/v0.3.0-rc1 )
